services:
  user-management:
    build:
      context: ./services/user-management
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=sqlserver://sa:AmanahProP@55w0rd@db:1433?database=AmanahDb
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - infras_network

networks:
  infras_network:
    driver: bridge

