filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: # Use add_docker_metadata for Docker container logs
          host: "unix:///var/run/docker.sock"
      - add_host_metadata: ~ # Adds metadata about the host system

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

# Enable logging for troubleshooting
logging.level: info # Set logging level to info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644
