metricbeat.modules:

# Docker metrics
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

# System metrics
- module: system
  metricsets: ["cpu", "memory", "network", "filesystem", "diskio"]
  period: 10s

# Redis metrics
- module: redis
  metricsets: ["info", "keyspace"]
  hosts: ["redis:6379"]
  period: 10s

# RabbitMQ metrics
- module: rabbitmq
  metricsets: ["node", "queue"]
  hosts: ["http://rabbitmq:15672"]
  username: admin
  password: AmanahProP@55w0rd

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
