global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"


scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:9419']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'mssql'
    static_configs:
      - targets: ['mssql-exporter:9182']

  - job_name: "node_exporter"
    static_configs:
      - targets: ['node-exporter:9100']