// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ba": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new BA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BAs"
                ],
                "summary": "Create BA",
                "parameters": [
                    {
                        "description": "BA Data",
                        "name": "ba",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BADTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created BA",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ba/filter": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Filter BAs by organization ID, BA ID, and project ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BAs"
                ],
                "summary": "Filter BAs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organization ID",
                        "name": "organization_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BA"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ba/{ba_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing BA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BAs"
                ],
                "summary": "Update BA",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BA Data",
                        "name": "ba",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BADTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated BA",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "BA Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing BA",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BAs"
                ],
                "summary": "Delete BA",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "BA Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ba/{ba_id}/sections": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new BA Section",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BASections"
                ],
                "summary": "Create BA Section",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BA Section Data",
                        "name": "section",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BASectionDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created BA Section",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ba/{ba_id}/sections/{section_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing BA Section",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BASections"
                ],
                "summary": "Update BA Section",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Section ID",
                        "name": "section_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BA Section Data",
                        "name": "section",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BASectionDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated BA Section",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "BA Section Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing BA Section",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BASections"
                ],
                "summary": "Delete BA Section",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Section ID",
                        "name": "section_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "BA Section Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ba/{ba_id}/sections/{section_id}/details": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new BA Detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BADetails"
                ],
                "summary": "Create BA Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Section ID",
                        "name": "section_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BA Detail Data",
                        "name": "detail",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BADetailDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created BA Detail",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ba/{ba_id}/sections/{section_id}/details/{detail_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing BA Detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BADetails"
                ],
                "summary": "Update BA Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Section ID",
                        "name": "section_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Detail ID",
                        "name": "detail_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BA Detail Data",
                        "name": "detail",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BADetailDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated BA Detail",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "BA Detail Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing BA Detail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BADetails"
                ],
                "summary": "Delete BA Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Section ID",
                        "name": "section_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Detail ID",
                        "name": "detail_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "BA Detail Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ba/{ba_id}/sections/{section_id}/details/{detail_id}/progress": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new BA Progress entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BAProgress"
                ],
                "summary": "Create BA Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Detail ID",
                        "name": "detail_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BA Progress Data",
                        "name": "progress",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BAProgressDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created BA Progress",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ba/{ba_id}/sections/{section_id}/details/{detail_id}/progress/{progress_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing BA Progress entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BAProgress"
                ],
                "summary": "Update BA Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Detail ID",
                        "name": "detail_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Progress ID",
                        "name": "progress_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BA Progress Data",
                        "name": "progress",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BAProgressDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated BA Progress",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "BA Progress Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing BA Progress entry",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BAProgress"
                ],
                "summary": "Delete BA Progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BA ID",
                        "name": "ba_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Detail ID",
                        "name": "detail_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Progress ID",
                        "name": "progress_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "BA Progress Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BADTO": {
            "type": "object",
            "properties": {
                "BADate": {
                    "$ref": "#/definitions/models.CustomDate"
                },
                "BASubject": {
                    "type": "string"
                },
                "OrganizationId": {
                    "type": "integer"
                },
                "ProjectId": {
                    "type": "integer"
                },
                "ProjectName": {
                    "type": "string"
                },
                "SphId": {
                    "type": "integer"
                }
            }
        },
        "dto.BADetailDTO": {
            "type": "object",
            "properties": {
                "DetailId": {
                    "type": "integer"
                },
                "DiscountPrice": {
                    "type": "number"
                },
                "ItemName": {
                    "type": "string"
                },
                "Quantity": {
                    "type": "number"
                },
                "SectionID": {
                    "type": "integer"
                },
                "Unit": {
                    "type": "string"
                },
                "UnitPrice": {
                    "type": "number"
                }
            }
        },
        "dto.BAProgressDTO": {
            "type": "object",
            "properties": {
                "BAProgressId": {
                    "type": "integer"
                },
                "CreatedBy": {
                    "type": "integer"
                },
                "DetailId": {
                    "type": "integer"
                },
                "OrganizationId": {
                    "type": "integer"
                },
                "ProgressCurrentM2": {
                    "type": "number"
                },
                "ProgressCurrentPercentage": {
                    "type": "number"
                },
                "ProgressPreviousM2": {
                    "type": "number"
                },
                "ProgressPreviousPercentage": {
                    "type": "number"
                },
                "UpdatedBy": {
                    "type": "integer"
                }
            }
        },
        "dto.BASectionDTO": {
            "type": "object",
            "properties": {
                "BAID": {
                    "type": "integer"
                },
                "BASectionId": {
                    "type": "integer"
                },
                "SectionName": {
                    "type": "string"
                }
            }
        },
        "models.BA": {
            "type": "object",
            "properties": {
                "badate": {
                    "description": "BA Date",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.CustomDate"
                        }
                    ]
                },
                "baid": {
                    "description": "Primary key",
                    "type": "integer"
                },
                "basubject": {
                    "description": "BA Subject",
                    "type": "string"
                },
                "createdAt": {
                    "description": "Creation timestamp",
                    "type": "string"
                },
                "createdBy": {
                    "description": "Created by user ID",
                    "type": "integer"
                },
                "deletedAt": {
                    "description": "Deletion timestamp",
                    "type": "string"
                },
                "deletedBy": {
                    "description": "Deleted by user ID",
                    "type": "integer"
                },
                "organizationId": {
                    "description": "Organization ID",
                    "type": "integer"
                },
                "projectId": {
                    "description": "Reference to Project ID",
                    "type": "integer"
                },
                "projectName": {
                    "description": "Project Name",
                    "type": "string"
                },
                "recepientName": {
                    "description": "Recepient Name",
                    "type": "string"
                },
                "sections": {
                    "description": "Relationship to BASection",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BASection"
                    }
                },
                "sphId": {
                    "description": "Reference to SPH ID",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "Update timestamp",
                    "type": "string"
                },
                "updatedBy": {
                    "description": "Updated by user ID",
                    "type": "integer"
                }
            }
        },
        "models.BADetail": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Creation timestamp",
                    "type": "string"
                },
                "createdBy": {
                    "description": "Created by user ID",
                    "type": "integer"
                },
                "deletedAt": {
                    "description": "Deletion timestamp",
                    "type": "string"
                },
                "deletedBy": {
                    "description": "Deleted by user ID",
                    "type": "integer"
                },
                "detailId": {
                    "description": "Primary key",
                    "type": "integer"
                },
                "discountPrice": {
                    "description": "Discounted price of the item",
                    "type": "number"
                },
                "itemName": {
                    "description": "Item Name",
                    "type": "string"
                },
                "organizationId": {
                    "description": "Organization ID",
                    "type": "integer"
                },
                "progress": {
                    "description": "Relationship to BAProgress",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BAProgress"
                    }
                },
                "quantity": {
                    "description": "Quantity",
                    "type": "number"
                },
                "sectionID": {
                    "description": "Reference to Section ID",
                    "type": "integer"
                },
                "sphItemId": {
                    "description": "Reference to SPH Item",
                    "type": "integer"
                },
                "totalPrice": {
                    "description": "Discounted price of the item",
                    "type": "number"
                },
                "unit": {
                    "description": "Unit",
                    "type": "string"
                },
                "unitPrice": {
                    "description": "Unit price of the item",
                    "type": "number"
                },
                "updatedAt": {
                    "description": "Update timestamp",
                    "type": "string"
                },
                "updatedBy": {
                    "description": "Updated by user ID",
                    "type": "integer"
                },
                "weightPercentage": {
                    "description": "Weight Percentage",
                    "type": "number"
                }
            }
        },
        "models.BAProgress": {
            "type": "object",
            "properties": {
                "baprogressId": {
                    "description": "Primary key",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "Creation timestamp",
                    "type": "string"
                },
                "createdBy": {
                    "description": "Created by user ID",
                    "type": "integer"
                },
                "deletedAt": {
                    "description": "Deletion timestamp",
                    "type": "string"
                },
                "deletedBy": {
                    "description": "Deleted by user ID",
                    "type": "integer"
                },
                "detailId": {
                    "description": "Reference to Detail ID",
                    "type": "integer"
                },
                "organizationId": {
                    "description": "Organization ID",
                    "type": "integer"
                },
                "progressCurrentM2": {
                    "description": "Current progress in M2",
                    "type": "number"
                },
                "progressCurrentPercentage": {
                    "description": "Current progress percentage",
                    "type": "number"
                },
                "progressPreviousM2": {
                    "description": "Previous progress in M2",
                    "type": "number"
                },
                "progressPreviousPercentage": {
                    "description": "Previous progress percentage",
                    "type": "number"
                },
                "updatedAt": {
                    "description": "Update timestamp",
                    "type": "string"
                },
                "updatedBy": {
                    "description": "Updated by user ID",
                    "type": "integer"
                }
            }
        },
        "models.BASection": {
            "type": "object",
            "properties": {
                "baid": {
                    "description": "Reference to BA ID",
                    "type": "integer"
                },
                "basectionId": {
                    "description": "Primary key",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "Creation timestamp",
                    "type": "string"
                },
                "createdBy": {
                    "description": "Created by user ID",
                    "type": "integer"
                },
                "deletedAt": {
                    "description": "Deletion timestamp",
                    "type": "string"
                },
                "deletedBy": {
                    "description": "Deleted by user ID",
                    "type": "integer"
                },
                "details": {
                    "description": "Relationship to BADetail",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BADetail"
                    }
                },
                "organizationId": {
                    "description": "Organization ID",
                    "type": "integer"
                },
                "sectionName": {
                    "description": "Section Name",
                    "type": "string"
                },
                "sphSectionId": {
                    "description": "Reference to SphSectionId",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "Update timestamp",
                    "type": "string"
                },
                "updatedBy": {
                    "description": "Updated by user ID",
                    "type": "integer"
                }
            }
        },
        "models.CustomDate": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Provide your JWT token with \"Bearer \" prefix, e.g., \"Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "BA Management Services API",
	Description:      "This is the SPH Management Services API documentation for managing BA, and reconciliations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
