definitions:
  dto.ProjectDTO:
    properties:
      Description:
        description: Project Description
        type: string
      EndDate:
        $ref: '#/definitions/models.CustomDate'
      Location:
        description: Project Location
        type: string
      ProjectID:
        description: Project ID
        type: integer
      ProjectName:
        description: Project Name (Required)
        type: string
      StartDate:
        $ref: '#/definitions/models.CustomDate'
      Status:
        description: Project Status
        type: string
    required:
    - ProjectName
    type: object
  models.CustomDate:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact: {}
  description: This is the Project Management Services API documentation for managing
    project, and reconciliations.
  title: Project Management Services API
  version: "1.0"
paths:
  /api/projects:
    post:
      consumes:
      - application/json
      description: Create a new project
      parameters:
      - description: Project Data
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/dto.ProjectDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created Project
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create Project
      tags:
      - Projects
  /api/projects/{project_id}:
    delete:
      description: Delete a project by ID
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Project Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete Project
      tags:
      - Projects
    put:
      consumes:
      - application/json
      description: Update an existing project
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: integer
      - description: Project Data
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/dto.ProjectDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Updated Project
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Project Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update Project
      tags:
      - Projects
  /api/projects/search:
    get:
      description: Search projects by organization ID and query string
      parameters:
      - description: Organization ID
        in: query
        name: organization_id
        required: true
        type: integer
      - description: Search Query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ProjectDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Search Projects
      tags:
      - Projects
securityDefinitions:
  BearerAuth:
    description: Provide your JWT token with "Bearer " prefix, e.g., "Bearer <token>"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
